using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnesComp.Models
{
    public static class DbInitializer
    {
        public static void Seed(AppDbContext context)
        {
            if (!context.Equipments.Any())
            {
                context.AddRange(
                    new Equipment { Name = "Krom Ayak", Price = 12.95M, ShortDescription = "Lorem ipsum dolor", LongDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare mollis enim, non accumsan enim consectetur a. Donec eros ligula, faucibus eget consequat sed, congue ac enim. Phasellus sed dignissim mauris. Nullam quis suscipit arcu. Nullam pulvinar nunc et ligula dignissim elementum. Vivamus nec maximus augue. Ut nibh dolor, euismod ut aliquam viverra, feugiat at dui. Sed tempus eget purus dictum eleifend. Donec gravida turpis a viverra varius. Aliquam erat volutpat. Morbi et vehicula felis. Duis tincidunt lacus vitae finibus tempus. Ut gravida neque vel libero tempor mollis.", ImageUrl = "/images/big/1.jpg", IsEquipmentOfTheWeek = true, ImageThumbnailUrl = "/images/small/1.jpg" },
                new Equipment { Name = "Plastik Tutamak ", Price = 18.95M, ShortDescription = "Lorem ipsum dolor", LongDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare mollis enim, non accumsan enim consectetur a. Donec eros ligula, faucibus eget consequat sed, congue ac enim. Phasellus sed dignissim mauris. Nullam quis suscipit arcu. Nullam pulvinar nunc et ligula dignissim elementum. Vivamus nec maximus augue. Ut nibh dolor, euismod ut aliquam viverra, feugiat at dui. Sed tempus eget purus dictum eleifend. Donec gravida turpis a viverra varius. Aliquam erat volutpat. Morbi et vehicula felis. Duis tincidunt lacus vitae finibus tempus. Ut gravida neque vel libero tempor mollis.", ImageUrl = "/images/big/2.jpg", IsEquipmentOfTheWeek = false, ImageThumbnailUrl = "/images/small/2.jpg" },
                new Equipment { Name = "Poliamid Ayak", Price = 18.95M, ShortDescription = "Lorem ipsum dolor", LongDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare mollis enim, non accumsan enim consectetur a. Donec eros ligula, faucibus eget consequat sed, congue ac enim. Phasellus sed dignissim mauris. Nullam quis suscipit arcu. Nullam pulvinar nunc et ligula dignissim elementum. Vivamus nec maximus augue. Ut nibh dolor, euismod ut aliquam viverra, feugiat at dui. Sed tempus eget purus dictum eleifend. Donec gravida turpis a viverra varius. Aliquam erat volutpat. Morbi et vehicula felis. Duis tincidunt lacus vitae finibus tempus. Ut gravida neque vel libero tempor mollis.", ImageUrl = "/images/big/3.jpg", IsEquipmentOfTheWeek = false, ImageThumbnailUrl = "/images/small/3.jpg" },
                new Equipment { Name = "Plastik Kol", Price = 15.95M, ShortDescription = "Lorem ipsum dolor", LongDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare mollis enim, non accumsan enim consectetur a. Donec eros ligula, faucibus eget consequat sed, congue ac enim. Phasellus sed dignissim mauris. Nullam quis suscipit arcu. Nullam pulvinar nunc et ligula dignissim elementum. Vivamus nec maximus augue. Ut nibh dolor, euismod ut aliquam viverra, feugiat at dui. Sed tempus eget purus dictum eleifend. Donec gravida turpis a viverra varius. Aliquam erat volutpat. Morbi et vehicula felis. Duis tincidunt lacus vitae finibus tempus. Ut gravida neque vel libero tempor mollis.", ImageUrl = "/images/big/4.jpg", IsEquipmentOfTheWeek = false, ImageThumbnailUrl = "/images/small/4.jpg" },
                new Equipment { Name = "Paslanmaz Civata", Price = 13.95M, ShortDescription = "Lorem ipsum dolor", LongDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare mollis enim, non accumsan enim consectetur a. Donec eros ligula, faucibus eget consequat sed, congue ac enim. Phasellus sed dignissim mauris. Nullam quis suscipit arcu. Nullam pulvinar nunc et ligula dignissim elementum. Vivamus nec maximus augue. Ut nibh dolor, euismod ut aliquam viverra, feugiat at dui. Sed tempus eget purus dictum eleifend. Donec gravida turpis a viverra varius. Aliquam erat volutpat. Morbi et vehicula felis. Duis tincidunt lacus vitae finibus tempus. Ut gravida neque vel libero tempor mollis.", ImageUrl = "/images/big/5.png", IsEquipmentOfTheWeek = false, ImageThumbnailUrl = "/images/small/5.png" },
                new Equipment { Name = "Sustalı Kol ", Price = 17.95M, ShortDescription = "Lorem ipsum dolor", LongDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare mollis enim, non accumsan enim consectetur a. Donec eros ligula, faucibus eget consequat sed, congue ac enim. Phasellus sed dignissim mauris. Nullam quis suscipit arcu. Nullam pulvinar nunc et ligula dignissim elementum. Vivamus nec maximus augue. Ut nibh dolor, euismod ut aliquam viverra, feugiat at dui. Sed tempus eget purus dictum eleifend. Donec gravida turpis a viverra varius. Aliquam erat volutpat. Morbi et vehicula felis. Duis tincidunt lacus vitae finibus tempus. Ut gravida neque vel libero tempor mollis.", ImageUrl = "/images/big/6.jpg", IsEquipmentOfTheWeek = false, ImageThumbnailUrl = "/images/small/6.jpg" },
                new Equipment { Name = "Galvanizli Ayak", Price = 15.95M, ShortDescription = "Lorem ipsum dolor", LongDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare mollis enim, non accumsan enim consectetur a. Donec eros ligula, faucibus eget consequat sed, congue ac enim. Phasellus sed dignissim mauris. Nullam quis suscipit arcu. Nullam pulvinar nunc et ligula dignissim elementum. Vivamus nec maximus augue. Ut nibh dolor, euismod ut aliquam viverra, feugiat at dui. Sed tempus eget purus dictum eleifend. Donec gravida turpis a viverra varius. Aliquam erat volutpat. Morbi et vehicula felis. Duis tincidunt lacus vitae finibus tempus. Ut gravida neque vel libero tempor mollis.", ImageUrl = "/images/big/7.jpg", IsEquipmentOfTheWeek = false, ImageThumbnailUrl = "/images/small/7.jpg" },
                new Equipment { Name = "Sabitlenebilir Ayak ", Price = 12.95M, ShortDescription = "Lorem ipsum dolor", LongDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare mollis enim, non accumsan enim consectetur a. Donec eros ligula, faucibus eget consequat sed, congue ac enim. Phasellus sed dignissim mauris. Nullam quis suscipit arcu. Nullam pulvinar nunc et ligula dignissim elementum. Vivamus nec maximus augue. Ut nibh dolor, euismod ut aliquam viverra, feugiat at dui. Sed tempus eget purus dictum eleifend. Donec gravida turpis a viverra varius. Aliquam erat volutpat. Morbi et vehicula felis. Duis tincidunt lacus vitae finibus tempus. Ut gravida neque vel libero tempor mollis.", ImageUrl = "/images/big/8.jpg", IsEquipmentOfTheWeek = true, ImageThumbnailUrl = "/images/small/8.jpg" },
                new Equipment { Name = "Kauçuk Blok", Price = 15.95M, ShortDescription = "Lorem ipsum dolor", LongDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare mollis enim, non accumsan enim consectetur a. Donec eros ligula, faucibus eget consequat sed, congue ac enim. Phasellus sed dignissim mauris. Nullam quis suscipit arcu. Nullam pulvinar nunc et ligula dignissim elementum. Vivamus nec maximus augue. Ut nibh dolor, euismod ut aliquam viverra, feugiat at dui. Sed tempus eget purus dictum eleifend. Donec gravida turpis a viverra varius. Aliquam erat volutpat. Morbi et vehicula felis. Duis tincidunt lacus vitae finibus tempus. Ut gravida neque vel libero tempor mollis.", ImageUrl = "/images/big/9.jpg", IsEquipmentOfTheWeek = true, ImageThumbnailUrl = "/images/small/9.jpg" },
                new Equipment { Name = "Denge Ayağı", Price = 15.95M, ShortDescription = "Lorem ipsum dolor", LongDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare mollis enim, non accumsan enim consectetur a. Donec eros ligula, faucibus eget consequat sed, congue ac enim. Phasellus sed dignissim mauris. Nullam quis suscipit arcu. Nullam pulvinar nunc et ligula dignissim elementum. Vivamus nec maximus augue. Ut nibh dolor, euismod ut aliquam viverra, feugiat at dui. Sed tempus eget purus dictum eleifend. Donec gravida turpis a viverra varius. Aliquam erat volutpat. Morbi et vehicula felis. Duis tincidunt lacus vitae finibus tempus. Ut gravida neque vel libero tempor mollis.", ImageUrl = "/images/big/10.jpg", IsEquipmentOfTheWeek = false, ImageThumbnailUrl = "/images/small/10.jpg" },
                new Equipment { Name = "Çelik Kol ", Price = 18.95M, ShortDescription = "Lorem ipsum dolor", LongDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare mollis enim, non accumsan enim consectetur a. Donec eros ligula, faucibus eget consequat sed, congue ac enim. Phasellus sed dignissim mauris. Nullam quis suscipit arcu. Nullam pulvinar nunc et ligula dignissim elementum. Vivamus nec maximus augue. Ut nibh dolor, euismod ut aliquam viverra, feugiat at dui. Sed tempus eget purus dictum eleifend. Donec gravida turpis a viverra varius. Aliquam erat volutpat. Morbi et vehicula felis. Duis tincidunt lacus vitae finibus tempus. Ut gravida neque vel libero tempor mollis.", ImageUrl = "/images/big/11.jpg", IsEquipmentOfTheWeek = false, ImageThumbnailUrl = "/images/small/11.jpg" }
                    );
                context.SaveChanges();
            }
        }
    }
}
